### ISSUE TITLE
Any chance to support more GD chips?

### ISSUE THREAD

**Issue by me21** [maxgerhardt/pio-gd32f130c6#4]
Hello,

Do you plan to support other GD chips like GD32F103CBT6, etc.? Maybe you could give any tips simple enough to do it myself?

**Comment by maxgerhardt** [comment]
This repository is outdated because me and a bunch of other people (which even includes GigaDevice employees) have started to create a much, much better PlatformIO integration for GigaDevice chips. The one you refer to ~~is also fully supported in there~~ will be supported very soon. Please read through https://github.com/platformio/platformio-core/issues/3927#issuecomment-888465652 and the repos linked therein. 

In the meantime I'm putting that in the README to use the other repositories instead.
